#!/bin/bash

# Try to use the destination package var, or use default if not specified.
if [ -n "$DSTROOT" ]; then
    apio_path="$DSTROOT/apio"
else
    apio_path="/Applications/apio"
fi

echo "Apio postinstall: DSTROOT   = [${DSTROOT}]"
echo "Apio postinstall: apio_path = [${apio_path}]"

# Write the path. New shells will have it in the PATH.
echo "${apio_path}" > /etc/paths.d/apio
