name: build-darwin-arm64-installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 👈 Enables manual trigger

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust version as needed
          
      - name: Checkout This Repository
        uses: actions/checkout@v4
        with:
          path: this-repo

      - name: Checkout Apio Repository
        uses: actions/checkout@v4
        with:
          repository: "zapta/apio_dev"
          path: apio-repo

      - name: Install the apio package.
        run: |
          python -m pip install --upgrade pip
          pip install -e apio-repo

      - name: Setup working directories.
        run: |
          mkdir _work
          mkdir _dist
          pwd
          ls -la .

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Run PyInstaller
        run: |
          pyinstaller --workpath _work --distpath _dist this-repo/.github/workflows/apio.spec
          pwd
          ls -al _dist
          pwd
          ls -al _dist/apio

      - name: Run PkgBuild
        run: |
          pkgbuild --root _dist \
                   --install-location /Applications \
                   --identifier "io.github.fpgawars.apio" \
                   --version "0.9.6" \
                   --ownership recommended \
                   apio-component.pkg
          pwd
          ls -al
         

      #- name: Upload Binary Artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: macos-binary
      #    path: dist/your_script  # Adjust if using a different name
