name: build-darwin-arm64-installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 👈 Enables manual trigger

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust version as needed
          
      - name: Checkout This Repository
        uses: actions/checkout@v4
        with:
          path: this-repo

      - name: Checkout Apio Repository
        uses: actions/checkout@v4
        with:
          repository: "zapta/apio_dev"
          path: apio-repo

      - name: Install the apio package.
        run: |
          python -m pip install --upgrade pip
          pip install -e apio-repo

      - name: Setup working directories.
        run: |
          mkdir _work
          mkdir _dist
          echo "current dir:"
          pwd
          ls -la .

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Run PyInstaller
        run: |
          pyinstaller --workpath _work --distpath _dist this-repo/.github/workflows/apio.spec
          echo "_dist:"
          ls -al _dist
          echo "_dist/apio:"
          ls -al _dist/apio
         

      #- name: Upload Binary Artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: macos-binary
      #    path: dist/your_script  # Adjust if using a different name
