name: Build macOS Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust version as needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build Binary with PyInstaller
        run: |
          pyinstaller --onefile your_script.py  # Adjust as needed

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: dist/your_script  # Adjust if using a different name
